# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Agnibha Banerjee
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Exoplanet Astronomer, PhD candidate and Data Scientist. This is my personal website where I share
  my projects in astronomy, machine learning, and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://riobanerjee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  riobanerjee

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
      related: false

# Site Author
author:
  name: "Agnibha Banerjee"
  avatar: "/assets/images/profile/avatar.jpg"
  bio: ""
  location: "United Kingdom"
  links:
    # - label: "Email"
    #   icon: "fas fa-fw fa-envelope-square"
    #   url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/riobanerjee"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/agnibha-banerjee-astro"
    - label: "ORCiD"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-9124-6537"

# Analytics
analytics:
  provider: "google-gtag"  # For GA4
  google:
    tracking_id: "G-K0QJ09YYD5"  # Replace with your tracking ID

# Reading Files
include:
  - _pages

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - _templates/
  - cv
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
